name: DayZ
version: 1.0.0
description: Adds in some mechanics from the game "DayZ"
author: Shades161 (NovaFox161)
website: www.cloudcraftgaming.com

main: com.cloudcraftgaming.dayz.Main

commands:
  dayz:
    description: Base command for the DayZ plugin.
    permission: DayZ.admin
  zone:
    description: Displays zone player is in.

permissions:
  DayZ.admin:
    description: Allows use of the dayz command.
    default: op